---
- name: Import RPM key
  ansible.builtin.rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

- name: Install MariaDB
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ packages }}"
  notify: Start MariaDB
  tags:
    - installation
    - packages

- name: Configure bind address
  ansible.builtin.lineinfile:
    dest: /etc/my.cnf.d/mariadb-server.cnf
    regexp: \#bind-address
    line: bind-address            = {{ bind_address }}
  tags:
    - configuration
    - bind-address
